[package]
name = "tux-farming"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = { version = "22.0.8" }
stellar-contract-utils = { workspace = true }

[dev-dependencies]
soroban-sdk = { version = "22.0.8", features = ["testutils"] }